### ISSUE TITLE
Problem with migrating views/charts/dashboards from V9.x to < V9

### ISSUE THREAD

**Issue by jrdnmckl** [a33ik/PersonalViewChartDBTransferTool#1]
There seems to be an issue with transferring personal views, charts and dashboards from instances that have version 9.x installed to destination instances with versions less than V9. In my case, the Source Instance has Version **9.1.0.1117** and the Destination instance has **Version 8.2.2.2464**. 

I've successfully used your plugin to transfer from V9.1 to V9.1 environments, so I think this is a versioning problem. Please advise. Thanks!

**Comment by AndrewButenko** [comment]
Hello Jordan,
Appreciate your report. Issue should be fixed now.
Closing this issue.
Andrew
