### ISSUE TITLE
Can't map AAD Group Teams

### ISSUE THREAD

**Issue by simes1** [a33ik/PersonalViewChartDBTransferTool#10]
I've found this an excellent and very useful tool in the past but it's becoming increasingly hard to use nowadays because it doesn't seem to support the new AAD Group Teams.

Please allow AAD Group Teams to be mapped and used just like Owner Teams.

Regards

--
Simon

**Comment by AndrewButenko** [comment]
Hello Simon,
I haven't used this AAD Group Teams functionality. I will look it up.
Andrew

**Comment by simes1** [comment]
They are the new Teams where Team membership is synced to an AAD Security or Office 365 Group.  Introduced (rather quietly) around 2 years ago I think...

**Comment by AndrewButenko** [comment]
Any chance you can give me access to the instance where I can reproduce it straight away without wasting time for building the environment?

**Comment by simes1** [comment]
Unfortunately I don't think I would be allowed to do that - it's not my environment.

It is very easy to create the AAD Group Teams in D365.  Even if you don't have admin rights in AAD to create a new one to test with all you need is the GUID of an existing AAD Security or AAD Office Group with Membership Type "Assigned" and you can create a Group Team for it in D365.  Alternatively, (later in the week), I should be able to show you in a Teams session or recreate this in one of my own environments to which I could then give you access.

However, I suspect all we are talking about here is modifying the filter on the list of Teams used by your tool from Team Type = Owner to something like Team Type = Owner, AAD Security Group or AAD Office Group or possibly just Team Type <> Access?

**Comment by AndrewButenko** [comment]
Hello,
I work on the update to the plugin and this functionality will be available in the next release.
Thanks,
Andrew

**Comment by AndrewButenko** [comment]
@simes1 fixed. Please download the latest version of the plugin from the XrmToolBox plugins store.
