### ISSUE TITLE
Broken with latest version of XRMToolBox

### ISSUE THREAD

**Issue by simes1** [a33ik/PersonalViewChartDBTransferTool#11]
I updated XRMToolBox recently and now your excellent tool appears not to load users or teams at all:

![image](https://user-images.githubusercontent.com/11423243/124642794-273a9000-de88-11eb-91fb-6bcf603feb05.png)

**Comment by AndrewButenko** [comment]
Thanks for the heads up. I will check it out.

**Comment by simes1** [comment]
Actually I'm beginning to think this is an issue with XTB itself rather than your tool.  I've noticed it in some other plug-ins now and if you wait (really quite a long time in my case) for the error message to show (with your tool after connecting to both source **and** destination) then everything works...

**Comment by simes1** [comment]
Looks like this was a corrupted XTB metadata cache.  Deleting the files in the MetaData cache folder seems to have fixed the problem - not sure what caused it.
