### ISSUE TITLE
Error when tried to open Load/Migrate Personal Views

### ISSUE THREAD

**Issue by kali-devineni** [a33ik/PersonalViewChartDBTransferTool#2]
Here is the Error

Unable to cast object of type 'Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClient' to type 'Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy

**Comment by AndrewButenko** [comment]
What's version of XrmToolbox that you use? I can't reproduce your error. I'm on v1.2018.10.29. Also I move records Online 9.1 -> Online 9.1.

**Comment by kali-devineni** [comment]
Here is my version

[cid:image001.png@01D4C86C.B1C1D380]

**Comment by CHMoeller** [comment]
I have the same problem, if I connect to a onprem system. 
Problem for receive the User of a CRM2011RU18 oder Dynamics 365 (8.2.2)
Is it possible to connect to an onprem System?

To receive the user from an online system is no problem.

**Comment by AndrewButenko** [comment]
Hello, is it on-prem with IFD or just with AD?

**Comment by CHMoeller** [comment]
It s only AD. No https, IFD. XrmToolBox has connection successful to source (onprem) and destination (online).
XrmToolBox runs on the onprem environment.

**Comment by simes1** [comment]
I also have this problem (also similar one with Personal User Views Migration plug-in).


D365CE Online: v9.1.0.5426

XRMToolbox: 1.2019.6.33

This Plug-in: 1.0.0.6

![image](https://user-images.githubusercontent.com/11423243/59203136-e03d1c00-8b95-11e9-86ed-b9898682a3fa.png)

**Comment by simes1** [comment]
This appears to be because this plug-in (and a whole load of others) don't appear to have been updated for the latest version of XRMToolbox:

https://github.com/MscrmTools/XrmToolBox/issues/868

**Comment by AndrewButenko** [comment]
Hello,
I updated the code. Please download the latest update.
Thanks,
Andrew

**Comment by simes1** [comment]
Great that appears to work with the new version (and orders the views more sensibly in the tree view).

It would be good to be able to access views for disabled users/teams as well as enabled ones.  See https://github.com/a33ik/PersonalViewChartDBTransferTool/issues/4
