### ISSUE TITLE
Cant migrate personal views - unable to read user password

### ISSUE THREAD

**Issue by sgbel** [a33ik/PersonalViewChartDBTransferTool#5]
Hello, I get the error above - do I have to configure the plugin somewhere else? 
Thanks.

**Comment by sgbel** [comment]
(my connection state is 'Connected' on both source and target instances)

**Comment by AndrewButenko** [comment]
Hello,
So what is the error?
Andrew

**Comment by sgbel** [comment]
"Cant migrate personal views - unable to read user password"

**Comment by AndrewButenko** [comment]
When does it occur? Also can I have a screenshot?

**Comment by sgbel** [comment]
![clicking_on_migrate_personal_views](https://user-images.githubusercontent.com/65967319/82927599-d95f1300-9f78-11ea-8d37-63b72fd6e60a.png)

**Comment by sgbel** [comment]
![clicking_on_personal_views](https://user-images.githubusercontent.com/65967319/82927685-fb589580-9f78-11ea-8149-30f330e36cc6.png)

**Comment by sgbel** [comment]
The first image is from when I click "migrate personal views". The second from when I click "load personal views". Thanks

**Comment by sgqub** [comment]
Hello Andrew, hope you are well. Have you any suggestions - nothing happens when I click on 'load personal views'. Thanks

**Comment by RobNightingale-LSL** [comment]
I have this too when using an MFA enabled/legacy login disabled account

**Comment by AndrewButenko** [comment]
Hello,
I work on the update to the plugin and this functionality will be available in the next release.
Thanks,
Andrew

**Comment by AndrewButenko** [comment]
@sgbel fixed. Please download the latest version of the plugin from the XrmToolBox plugins store.
