### ISSUE TITLE
Error loading Users and Teams

### ISSUE THREAD

**Issue by RobertSchouten** [a33ik/PersonalViewChartDBTransferTool#8]
When trying to load users and teams after connecting to 2 organisations that are 2011
i get the error 
'Team' entity doesn't contain attribute with Name = 'teamtype'.
and am unable to use the tool

**Comment by AndrewButenko** [comment]
Hello,
I work on the update to the plugin and this fix will be available in the next release.
Thanks,
Andrew

**Comment by AndrewButenko** [comment]
@RobertSchouten fixed. Please download the latest version of the plugin from the XrmToolBox plugins store.
